def report_agent(state):

    report = f"""
# VentureMind AI

## Startup Due Diligence Report

**Company:** {state["company_name"]}

**Website:** {state["website_url"]}

---

# Company Research

{state["research"]}

---

# Business Analysis

{state["business_analysis"]}

---

# Investment Recommendation

This report was generated using VentureMind AI's multi-agent analysis pipeline.

The analysis combines:

- Website Intelligence
- Company Research
- Competitor Analysis
- Market Analysis
- Risk Assessment
- Investment Scoring

### Disclaimer

This report is AI-generated and should be used as a decision-support tool. Final investment decisions should always include detailed financial, legal, technical, and market due diligence performed by human experts.

---

**Generated by VentureMind AI**
"""

    return {
        "report": report
    }